export const SETPRODUCT = "SETPRODUCT";

export const INIT_SET_PRODUCTS = "INIT_SET_PRODUCTS";
export const SUCCESS_SET_PRODUCTS = "SUCCESS_SET_PRODUCTS";
export const FAIL_SET_PRODUCTS = "FAIL_SET_PRODUCTS";
